site_name: '入門 Docker'

theme:
  name: 'material'
  language: 'ja'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  highlightjs: true
  hljs_languages:
    - yaml
    - dockerfile

extra:
  search:
    language: 'ja'

markdown_extensions:
  - 'admonition'
  - 'footnotes'
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true

google_analytics: ['UA-136697307-1', 'y-ohgi.com']

extra_css:
  - "assets/custom.css"

extra_javascript:
  - 'assets/custom.js'

nav:
  - 'Home': 'index.md'
  - 'はじめに':
    - 'Dockerとは': '1_introduction/docker.md'
    - 'VMとDocker': '1_introduction/vm-docker.md'
    - 'Hello Docker !': '1_introduction/hello-docker.md'
  - 'コンポーネント':
    - 'image': '2_component/image.md'
    - 'dockerfile': '2_component/dockerfile.md'
    - 'container': '2_component/container.md'
    - 'network': '2_component/network.md'
    - 'volume': '2_component/volume.md'
  - 'プロダクションでの活用':
    - 'デバッグ': '3_production/debug.md'
    - '設計': '3_production/design.md'
    - 'イメージの仕組み': '3_production/image.md'
    - 'Dockerfile': '3_production/dockerfile.md'
    - 'オーケストレーションツール': '3_production/orchestration.md'
    - 'docker-compose': '3_production/docker-compose.md'
    - 'セキュリティ': '3_production/security.md'
    - 'プロダクションへの導入': '3_production/introduction.md'
  - 'Tips':
    - 'tools': '4_tips/tools.md'
    - 'docker-compose': '4_tips/docker-compose.md'
