site_name: '入門 Docker'
site_description: プロダクションへ導入するために必要なDockerの概要から設計までを、なるべく最短経路で学ぶことが目的のハンズオン資料です。

theme:
  name: material
  language: ja
  palette:
    - schema: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  custom_dir: overrides
  features:
    - content.code.copy

plugin:
  search:
    language: 'ja'

markdown_extensions:
  - 'admonition'
  - 'footnotes'
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra:
  analytics:
    provider: google
    property: UA-136697307-1

extra_css:
  - 'assets/custom.css'

extra_javascript:
  - 'assets/custom.js'

nav:
  - Home: index.md
  - はじめに:
    - Dockerとは: 1_introduction/docker.md
    - VMとDocker: 1_introduction/vm-docker.md
    - Hello Docker !: 1_introduction/hello-docker.md
  - コンポーネント:
    - image: 2_component/image.md
    - Dockerfile: 2_component/dockerfile.md
    - container: 2_component/container.md
    - network: 2_component/network.md
    - volume: 2_component/volume.md
  - プロダクションでの活用:
    - セキュリティ: 3_production/security.md
    - マルチステージビルド: 3_production/multistage-build.md
    - イメージの仕組みと設計: 3_production/image-design.md
    - Dockerfileのベストプラクティス: 3_production/dockerfile.md
    - docker compose: 3_production/docker-compose.md
  - Tips:
    # - docker composeを使いこなす: 4_tips/docker-compose.md
    - オーケストレーションツール: 4_tips/orchestration.md
    - プロダクションへの導入: 4_tips/introduction.md
    - デバッグ: 4_tips/debug.md
    # - tools: 4_tips/tools.md
